name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Prepare release
        run: mvn release:prepare
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FULL_POWER }}
          ACTOR: ${{ github.actor }}

      - name: Perform release
        run: mvn release:perform
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_FULL_POWER }}
          ACTOR: ${{ github.actor }}



      # - name: Grant execute permissions for update-version.sh
      #  run: chmod +x ./update-version.sh
      #  working-directory: ./

      # - name: Update version # auto-increments +0.0.1, if not manually set
      #  run: ./update-version.sh
      #  working-directory: ./

      # - name: Build with Maven
      #  run: mvn clean install
      #  working-directory: ./

      #- name: Build and publish
      #  run: mvn clean deploy -s settings.xml
      #  working-directory: ./
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.PAT_FULL_POWER }}
      #    ACTOR: ${{ github.actor }}