name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Build and publish
        run: mvn clean deploy -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.LIB_PAT_CLASSIC_TOKEN }}
          ACTOR: ${{ github.actor }}