name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permissions for update-version.sh
        run: chmod +x ./update-version.sh
        working-directory: ./

      - name: Update version # auto-increments +0.0.1, if not manually set
        run: ./update-version.sh
        working-directory: ./

      - name: Commit and push updated version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update version to new version"
          git push https://<PAT_FULL_POWER>@github.com/AlekOmOm/library.git master
        working-directory: ./
        env:
          PAT_FULL_POWER: ${{ secrets.PAT_FULL_POWER }}

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./

      - name: Build and publish
        run: mvn clean deploy -s settings.xml
        working-directory: ./
        env:
          GITHUB_TOKEN: ${{ secrets.LIB_PAT_CLASSIC_TOKEN }}
          ACTOR: ${{ github.actor }}